# Generated by Django 4.2 on 2023-05-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
